server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  docker:
    compose:
      lifecycle-management: start_only
