CREATE TABLE IF NOT EXISTS t_users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    c_firstname  VARCHAR(50)                             NOT NULL,
    c_lastname   VARCHAR(50)                             NOT NULL,
    c_email      VARCHAR(50)                             NOT NULL,
    c_password   VARCHAR(255)                            NOT NULL,
    c_created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_t_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS t_users_roles
(
    user_id BIGINT NOT NULL,
    c_role  VARCHAR(32)
);

ALTER TABLE t_users
    ADD CONSTRAINT uc_t_users_c_email UNIQUE (c_email);

ALTER TABLE t_users_roles
    ADD CONSTRAINT fk_t_users_roles_on_user FOREIGN KEY (user_id) REFERENCES t_users (id);

CREATE TABLE IF NOT EXISTS t_projects
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    c_title       VARCHAR(255)                            NOT NULL,
    c_description TEXT,
    c_created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_t_projects PRIMARY KEY (id)
);

ALTER TABLE t_projects
    ADD CONSTRAINT FK_T_PROJECTS_ON_USER FOREIGN KEY (user_id) REFERENCES t_users (id);

CREATE TABLE IF NOT EXISTS t_time_records
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id      BIGINT,
    c_project_state VARCHAR(32),
    c_start_time    TIMESTAMP WITHOUT TIME ZONE,
    c_end_time      TIMESTAMP WITHOUT TIME ZONE,
    c_description   VARCHAR(255),
    CONSTRAINT pk_t_time_records PRIMARY KEY (id)
);

ALTER TABLE t_time_records
    ADD CONSTRAINT FK_T_TIME_RECORDS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES t_projects (id);
