CREATE TABLE IF NOT EXISTS t_users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    c_email     VARCHAR(255)                            NOT NULL,
    c_password  VARCHAR(255)                            NOT NULL,
    c_firstname VARCHAR(255)                            NOT NULL,
    c_lastname  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_t_users PRIMARY KEY (id)
);

ALTER TABLE t_users
    ADD CONSTRAINT uc_t_users_c_email UNIQUE (c_email);

CREATE TABLE IF NOT EXISTS t_users_roles
(
    user_id BIGINT       NOT NULL,
    c_role     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_t_users_roles PRIMARY KEY (user_id, c_role)
);

ALTER TABLE t_users_roles
    ADD CONSTRAINT fk_t_users_roles_on_c_user FOREIGN KEY (user_id) REFERENCES t_users (id) ON DELETE CASCADE ON UPDATE NO ACTION;


CREATE TABLE IF NOT EXISTS t_projects
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    c_title       VARCHAR(255)                            NOT NULL,
    c_description VARCHAR(255)                            NULL,
    c_start       TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_t_projects PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS t_time_records
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    project_id    BIGINT                                  NOT NULL,
    c_start_time  TIMESTAMP                               NOT NULL,
    c_end_time    TIMESTAMP                               NOT NULL,
    c_description TEXT                                    NULL,

    CONSTRAINT pk_t_time_records PRIMARY KEY (id),
    CONSTRAINT fk_t_time_records_on_c_user FOREIGN KEY (user_id) REFERENCES t_users (id) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT fk_t_time_records_on_c_project FOREIGN KEY (project_id) REFERENCES t_projects (id) ON DELETE CASCADE ON UPDATE NO ACTION
);
