CREATE TABLE IF NOT EXISTS records
(
    id         BIGSERIAL PRIMARY KEY,
    task_id    BIGINT NOT NULL UNIQUE REFERENCES tasks (id) ON DELETE CASCADE,
    start_time TIMESTAMP WITHOUT TIME ZONE,
    end_time   TIMESTAMP WITHOUT TIME ZONE
);